spring:
  application:
    name: ISH-UserMgmtService
  config:
    import: optional:configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true
  # Security configuration
  security:
    user:
      name: admin
      password: admin
#for  data source
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/InsuranceSystemForHealth
    username: root
    password: root

 # jpa  -hibernate proeprties
  jpa:
     show-sql: true
     database-platform: org.hibernate.dialect.MySQL8Dialect
     hibernate:
          ddl-auto: update
  # Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: lakshaychaudhary2003@gmail.com
    # For development, use a default password
    # For production, set the MAIL_PASSWORD environment variable
    password: ${MAIL_PASSWORD:kdvirgldcxfmnwiv}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

server:
   port:  4041

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

mailbody:
   registeruser:
        location:  classpath:in/lakshay/service/user_registration_body.txt
   registerworker:
        location:  classpath:in/lakshay/service/worker_registration_body.txt
   recoverpwd:
        location:  classpath:in/lakshay/service/recover_pwd_body.txt

# JWT Configuration
jwt:
  secret: defaultSecretKeyWhichShouldBeAtLeast256BitsLongForHS256Algorithm
  expiration: 604800000  # 7 days in milliseconds
  header: Authorization
  prefix: Bearer
  issuer: ish-health-system
  audience: ish-services

# Security Configuration

# Logging Configuration
logging:
  level:
    root: INFO
    in.lakshay: DEBUG
    org.springframework.web: DEBUG
    # Security logging removed
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/user-mgmt-service.log
    max-size: 10MB
    max-history: 10

