server:
  port: 8888
spring:
  application:
    name: ISH-ConfigServer-GIT
  cloud:
    config:
      server:
        bootstrap: false
        git:
          clone-on-start: true
          skipSslValidation: true
          uri: https://github.com/lakshay1341/ISH-ConfigServer-GIT
