eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7777
spring:
  application:
    name: ISH-CloudAPIGateway
  cloud:
    gateway:
      routes:
      - id: ISH-AdminService
        predicates:
        - Path=/plan-api/**
        uri: http://localhost:7074/
      - id: ISH-ApplicationRegistrationService
        predicates:
        - Path=/CitizenAR-api/**
        uri: http://localhost:7071/
      - id: ISH-BenefitIssuanceService
        predicates:
        - Path=/bi-api/**
        uri: http://localhost:7076/
      - id: ISH-CorrespondenceService
        predicates:
        - Path=/co-triggers-api/**
        uri: http://localhost:7075
      - id: ISH-DataCollectionService
        predicates:
        - Path=/dc-api/**
        uri: http://localhost:7072/
      - id: ISH-EligibilityDeterminationService
        predicates:
        - Path=/ed-api/**
        uri: http://localhost:7073/
      - id: ISH-GovernmentReportService
        predicates:
        - Path=/report-api/government/**
        uri: http://localhost:7077/
      - id: ISH-UserMgmtService
        predicates:
        - Path=/user-api/**
        uri: http://localhost:4041/
