eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7777
spring:
  application:
    name: ISH-CloudAPIGateway
  main:
    allow-bean-definition-overriding: true
  # Security configuration is now enabled
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: ISH-AdminService
        predicates:
        - Path=/plan-api/**
        uri: http://localhost:7074/
      - id: ISH-ApplicationRegistrationService
        predicates:
        - Path=/CitizenAR-api/**,/citizen-app/**
        uri: http://localhost:7071/
      - id: ISH-BenefitIssuanceService
        predicates:
        - Path=/bi-api/**
        uri: http://localhost:7076/
      - id: ISH-CorrespondenceService
        predicates:
        - Path=/co-triggers-api/**
        uri: http://localhost:7075
      - id: ISH-DataCollectionService
        predicates:
        - Path=/dc-api/**
        uri: http://localhost:7072/
      - id: ISH-EligibilityDeterminationService
        predicates:
        - Path=/ed-api/**
        uri: http://localhost:7073/
      - id: ISH-GovernmentReportService
        predicates:
        - Path=/report-api/government/**
        uri: http://localhost:7077/
      - id: ISH-UserMgmtService
        predicates:
        - Path=/user-api/**,/api/auth/**,/worker-api/**
        uri: http://localhost:4041/
        filters:
        - PreserveHostHeader
        - AddRequestHeader=X-Forwarded-Prefix, /api

# JWT Configuration
jwt:
  secret: defaultSecretKeyWhichShouldBeAtLeast256BitsLongForHS256Algorithm
  expiration: 604800000  # 7 days in milliseconds
  header: Authorization
  prefix: Bearer
  issuer: ish-health-system
  audience: ish-services

# Security Configuration
management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

# Logging Configuration
logging:
  level:
    root: INFO
    in.lakshay: DEBUG
    in.lakshay.filter: TRACE
    in.lakshay.security: TRACE
    in.lakshay.exception: TRACE
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/api-gateway.log
    max-size: 10MB
    max-history: 10
