server:
  port: 7072
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ISH-DataCollectionService

  # Data Source configuration
  datasource:
    url: jdbc:mysql://localhost:3306/InsuranceSystemForHealth
    username: root
    password: root

  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
