server:
  port: 7077
spring:
  application:
    name: ISH-ReportService
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/InsuranceSystemForHealth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka client configuration
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
