server:
  port: 7077
spring:
  application:
    name: ISH-ReportService
  config:
    import: optional:configserver:http://localhost:8888

# Eureka client configuration
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
