server:
  port: 7076
spring:
  config: 
     import: optional:configserver:http://localhost:8888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  application:
    name: ISH-BIService
eureka:
   client:
      service-url:
          default-zone: http://localhost:8761/eureka
      