# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: ISH-ApplicationRegistrationService
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 7071
ar:
  ssa-web:
    url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: california
