server:
  port: 7073
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ISH-EligibilityDeterminationService

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
