-- Increase the size of columns in the CITIZEN_APPLICATION table
ALTER TABLE CITIZEN_APPLICATION MODIFY COLUMN remark VARCHAR(1000);
ALTER TABLE CITIZEN_APPLICATION MODIFY COLUMN state_name VARCHAR(100);
ALTER TABLE CITIZEN_APPLICATION MODIFY COLUMN full_name VARCHAR(100);
ALTER TABLE CITIZEN_APPLICATION MODIFY COLUMN email VARCHAR(100);
ALTER TABLE CITIZEN_APPLICATION MODIFY COLUMN created_by VARCHAR(100);
ALTER TABLE CITIZEN_APPLICATION MODIFY COLUMN updated_by VARCHAR(100);
