spring:
  application:
    name: ISH-EurekaServer

# Server configuration
server:
  port: 8761

# Make this project as Eureka server by disabling parent Project's
# inherited properties values to false
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.eureka: INFO
    org.springframework.web: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/eureka-server.log
    max-size: 10MB
    max-history: 10
