# Application configuration
spring:
  application:
    name: ISH-ApplicationRegistrationService
  config:
    import: optional:configserver:http://localhost:8888

  # Data Source configuration
  datasource:
    url: jdbc:mysql://localhost:3306/InsuranceSystemForHealth
    username: root
    password: root

  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Server configuration
server:
  port: 7071

# Application specific properties
ar:
  ssa-web:
    url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: california
