server:
  port: 7076
spring:
  config:
     import: optional:configserver:http://localhost:8888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  application:
    name: ISH-BenefitIssuanceService
  
  # Data Source configuration
  datasource:
    url: jdbc:mysql://localhost:3306/InsuranceSystemForHealth
    username: root
    password: root

  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka client configuration
eureka:
   client:
      service-url:
          defaultZone: http://localhost:8761/eureka

# Benefit issuance configuration
benefit:
  issuance:
    output-file: beneficiries_list.csv
