spring:
  config: 
     import: optional:configserver:http://localhost:8888
  application:
     name: CorrespondenceAPI


  mail:
    host: smtp.gmail.com
    port: 587
    username: lakshaychaudhary2003@gmail.com
    password: dmcpenslsygkpgnw
    properties:
        mail:
          transport:
             protocol: smtp
          smtp: 
              port: 587
              auth: true
              starttls:
                  enable: true
                  required: true
server:
   port: 7075
eureka:
   client:
      service-url:
          default-zone: http://localhost:8761/eureka
   