spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ISH-CorrespondenceService

  mail:
    host: smtp.gmail.com
    port: 587
    username: lakshaychaudhary2003@gmail.com
    # For development, use a default password
    # For production, set the MAIL_PASSWORD environment variable
    password: ${MAIL_PASSWORD:kdvirgldcxfmnwiv}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

server:
  port: 7075

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Correspondence configuration
correspondence:
  pdf:
    output-dir: ./pdf-notices
