spring:
  config:
     import: optional:configserver:http://localhost:8888
  application:
     name: ISH-CorrespondenceService


  # Mail configuration
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: c71a548eca5cc6
    password: bae1a50130ba10
    properties:
        mail:
          transport:
             protocol: smtp
          smtp:
              auth: true
              starttls:
                  enable: true
                  required: true
server:
   port: 7075
eureka:
   client:
      service-url:
          defaultZone: http://localhost:8761/eureka

# Correspondence configuration
correspondence:
  pdf:
    output-dir: ./pdf-notices
