spring:
  config:
     import: optional:configserver:http://localhost:8888
  application:
     name: ISH-CorrespondenceService


  # Mail configuration moved to ConfigServer
  mail:
    properties:
        mail:
          transport:
             protocol: smtp
          smtp:
              auth: true
              starttls:
                  enable: true
                  required: true
server:
   port: 7075
eureka:
   client:
      service-url:
          defaultZone: http://localhost:8761/eureka

# Correspondence configuration
correspondence:
  pdf:
    output-dir: ./pdf-notices
